loginpage/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\superUserController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('home', [HomeController::class, 'index'])->name('home'); 
Route::group(['middleware' => ['super_admin']], function () {
Route::get('super_admin-view', [HomeController::class, 'super_adminView'])->name('super_admin.view');
}); 


Route::resource('order', OrderController::class);
Route::get('/order/fetchRate/{p}', 'OrderController@fetchRate');

Route::resource('user',UserController::class);
Route::resource('customer',CustomerController::class);
Route::resource('employee',EmployeeController::class);

//Route::get('/order/index', 'OrderController@index');
// Route::get('/order/create', 'OrderController@create');
// Route::get('/order/store', 'OrderController@store');
// Route::get('/order/show/{id}', 'OrderController@show');
// Route::get('/order/edit/{id}', 'OrderController@edit');
// Route::get('/order/update/{id}', 'OrderController@update');
// Route::get('/order/destroy/{id}','OrderController@destroy');

loginpage/app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
   protected $table='orders';  
   protected $fillable=['serial_No','name','total','date','max_no'];  
}

loginpage/app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use App\Product;
use App\OrderProduct;

use Illuminate\Support\Facades\DB;
class OrderController extends Controller
{
   
public function index()
    {
        $orders = Order::all();   
        return view('order/index', compact('orders'));
    }
public function create(Request $request)
    {
        $data = Product::all();
        return view('order/create', compact('data')); 
    }
public function fetchRate(Request $request,$pdct)
    {
        $rate = Product::select('rate')->where('id',$pdct)->first();
        return $rate; 
    }
public function store(Request $request)  
    {  
       $request->validate([  
            'name'     =>'required',
            'date'     =>'required',
            'product'  =>'required', 
            'rate'     =>'required', 
            'quantity' =>'required', 
        ]);

        $max_no = Order::max('max_no');
       if(isset($request->product)){
       if ($max_no==null) {
         
         $max_no = 1;
        } else {
         $max_no= $max_no+1 ;
      }
      $order = Order::create([
        'max_no'    => $max_no,
        'serial_No' => 'ord/'.$max_no.'/2022',
        'name'      => $request->name,
        'date'      => $request->date,
        'total'     => $request->grandtotal,
        ]);
      }
      
        // $order = new Order; 
        // $order->serial_No = $request->get('serial_No');    
        // $order->name      = $request->get('name');
        // $order->date      = $request->get('date'); 
        // $order->total     = $request->get('grandtotal'); 
        // $order->save(); 
        
        for ($i=0;$i<count($request->product);$i++ ){
        $data = OrderProduct::create([
            'order_id' => $order->id,
            'product'  => $request->product[$i],
            'rate'     => $request->rate[$i],
            'quantity' => $request->quantity[$i],
            'total'    => $request->total[$i],
        ]);
           }
        return redirect('order');
    } 
public function edit(Request $request, $id)  
    {  
       $order    = Order::find($id);
       $data     = Product::all(); 
       $products = OrderProduct::where('order_id', $id)->get();
       return view('order/edit', compact('order','data', 'products')); 
    }  
public function update(Request $request, $id)
{
        if($request->grandtotal!=0) {
        $order = Order::find($id); 
        $order->name      = $request->get('name'); 
        $order->date      = $request->get('date');
        $order->total     = $request->get('grandtotal');  
         
        $order->save();
                
        if(isset($request->edit_delete)) {
        $orderproduct = OrderProduct::where('id',$request->edit_delete)->delete();            
        }

        if (isset($request->edit_id)) {
        foreach ($request->edit_id as $key =>$edit_id ){
        $orderproduct = OrderProduct::where('id',$edit_id)->update([
            'order_id' => $order->id,
            'product'  => $request->edit_product[$key],
            'rate'     => $request->edit_rate[$key],
            'quantity' => $request->edit_quantity[$key],
            'total'    => $request->edit_total[$key],
            ]);
            }
        }

        if (isset($request->product)) {
        foreach ($request->product as $key =>$product ){
        $orderproduct = OrderProduct::where('id',$product)->create([
            'order_id' => $order->id,
            'product'  => $request->product[$key],
            'rate'     => $request->rate[$key],
            'quantity' => $request->quantity[$key],
            'total'    => $request->total[$key],
            ]);
            }
        }
    }

        return redirect('order');  
}

public function show($id){
    $orders  = Order::find (array($id));
    $products = OrderProduct::where('order_id', $id) ->get();
    
return view('order/show', compact('orders','products'));
}
// public function show($id)  
//     {  

//        $orders  = Order::find (array($id));
//        $products = OrderProduct::join('products','products.id' , '=', 'order_products.product')
//                 ->where('order_products.order_id', $id)

//        ->selectRaw('order_products.id,products.product,order_products.rate,order_products.quantity,order_products.total')
//        ->get();
       
       
//        return view('order/show', compact('orders','products')); 
//     } 
public function destroy($id)  
    {  
       $order=Order::find($id);  
       $order->delete();
       $products = OrderProduct::where('order_id', $id);
       $products->delete();

       return redirect('order');  
    } 
     

}

loginpage/resources/views/order/create.blade.php
@extends('layouts.app') 
@section('content')
<head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>  
<form method="POST" action="{{route('order.store')}}">
    @csrf    
           
        <div class="form-group">      
              <label for="name">Name:  
              <input type="text" class="form-control" name="name">
              </label><br/><br/> 
        </div>
        <div class="form-group">      
              <label for="date">Date : 
              <input type="date" class="form-control" name="date">
              </label><br/><br/>  
        </div>               


        <button class="btn btn-md btn-primary" id="addBtn" type="button">Add new Row
        </button>
        <br/>
   <table id="mytable"> 
       <thead>
             <th>ID </th>
             <th>Product</th>
             <th>Rate</th>
             <th>Quantity</th>
             <th>Total</th>
       </thead>
           <tbody id="tbody" class="tbody">
           <tr id="R${++rowIdx}">
                <td class="row-index text-center">
                <p>1</p></td>
                <td>
                    <select class="product" name="product[]" id="product" required>
                    <option value=''>Select product</option>
                  @foreach ($data as $row)
                    <option value="{{ $row->id }}" >{{$row->product }} 
                    </option>
                  @endforeach    
                    </select>
                </td>
                <td><input class="rate" id="rate" name="rate[]" required></td>
                <td><input class="quantity" id="quantity" name="quantity[]" required></td>
                <td><input class="total" id="total" name="total[]" readonly></td>
                <td><button type="delete" class="delete" >remove</button></td>
                </tr> 
             <tfoot>
                 <tr>
                     <th id="ttl" colspan="4">Grandtotal :</th>
                     <td><input class="grandtotal" id="grandtotal" name="grandtotal" readonly></td>
                 </tr>
             </tfoot>
          </tbody>
   </table>
     <footer>
       <button type="submit" class="btn-btn" >save</button> 
     </footer> 
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        var rowIdx = 1;
        $('#addBtn').on('click', function () {
            var flag =0;
            $('.product').each(function(){
            if ($(this).val()==''){
                flag=1;
             }
            });
            if(flag==0){
            $('#tbody').append(`<tr id="R${++rowIdx}">
                <td class="row-index text-center">
                <p>${rowIdx}</p></td>
                <td>
                    <select class="product" name="product[]" id="product" required>
                    <option value=''>Select product</option>
                  @foreach ($data as $row)
                    <option value="{{ $row->id }}" >{{$row->product }} 
                    </option>
                  @endforeach    
                    </select>
                </td>
                <td><input class="rate" id="rate" name="rate[]" required></td>
                <td><input class="quantity" id="quantity" name="quantity[]" required></td>
                <td><input class="total" id="total" name="total[]"readonly></td>
                <td><button type="delete" class="delete" >remove</button></td>
                </tr>`);
            }
           });
        $('#tbody').on("change","#product",function(){
            var parent = $(this).closest('tr');
            var pdct =$(parent).find('#product').val();
            $.ajax({
                type : 'get',
                url : '{{url("order/fetchRate")}}/'+pdct,
                data:{p:pdct},
                success: function(data){
                console.log(data);
                $(parent).find('#rate').val(data.rate);
                var c = calculate (parent);
                $(parent).find('#rate').val(c);
          }
      });

  }); 
        $('#tbody').on("change","#product",function(){
            var parent = $(this).closest('tr');
            var qntity = parent.find(".quantity").val("");
            var ttl    = parent.find(".total").val("");
             $(parent).$val(qntity);
             $(parent).$val(ttl); 
             });

        $('#tbody').on("keyup",".rate,.quantity",function(){
            var parent = $(this).closest('tr');
            var price =Number($(parent).find('.rate').val());
            var qntity = Number($(parent).find('.quantity').val());
            var ttl = Number(parseInt(price* qntity));
            if (price == "0" ){
                ttl=0;
                }
            if (qntity == "0" ){
                ttl=0; 
                }
            $(parent).find('.total').val(ttl); 
            grandTotal();
            });  


        function grandTotal(){
            var sum= 0;
            $('.total').each(function() {
            sum += parseInt($(this).val()|| 0);
            });
            $('#grandtotal').val(sum);
        }

        $("#mytable").on('click', '.delete', function () {
        var child = $(this).closest('tr').nextAll();
        child.each(function () {
            var id = $(this).attr('id');
            var idx = $(this).children('.row-index').children('p');
            var dig = parseInt(id.substring(1));
            idx.html(` ${dig - 1}`);
            $(this).attr('id', `R${dig - 1}`);
        });
            $(this).closest('tr').remove();
            rowIdx--;
            grandTotal();             
    });
        
});


</script>  
@endsection 

loginpage/resources/views/order/edit.blade.php
@extends('layouts.app') 
@section('content')  
<head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<form method="POST" id="edit_form"action="{{route('order.update',$order->id)}}">
    @csrf 
    @method('PUT')     
   
        <div class="form-group">      
        <label for="serial_No">Sl.No:
        <input type="text" class="form-control" name="name" value="{{$order->serial_No}}"readonly>  
        </label><br/><br/> 
        </div>     
        <div class="form-group">      
              <label for="name">Name:  
              <input type="text" class="form-control" name="name" value="{{$order->name}}">
              </label><br/><br/>  
        </div>
        <div class="form-group">      
              <label for="date">Date : 
              <input type="date" class="form-control" name="date" value="{{($order->date) }}">
              </label><br/><br/>   
        </div>               


        <button class="btn btn-md btn-primary" id="addBtn" type="button">Add new Row
        </button>
        <br>
        
   <table  id="mytable"> 
       <thead>
             <th>ID </th>
             <th>Product</th>
             <th>Rate</th>
             <th>Quantity</th>
             <th>Total</th>
       </thead>
           <tbody id="tbody" class="tbody">
           @foreach($products as $product) 
            <tr id="R${++rowIdx}">
                <td class="row-index text-center">
                <p>{{$loop->iteration}}</p></td>
                <td>
                    <input  type="hidden"  name="edit_id[]" id="edit_id" value="{{$product->id}}">
                    <select class="product" name="edit_product[]" id="product"  required>
                    <option value=''>Select product</option>
                  @foreach ($data as $row)
                  <option value="{{ $row->id }}" @if (old('product') == $row->id || $row->id == $product->product)selected  @endif >{{$row->product}} 
                  @endforeach    
                    </select>
                </td>
                <td><input class="rate" id="rate" name="edit_rate[]" value="{{$product->rate}}"required></td>
                <td><input class="quantity" id="quantity" name="edit_quantity[]" value="{{$product->quantity}}"required></td>
                <td><input class="total" id="total" name="edit_total[]" value="{{$product->total}}" readonly></td>
                <td><button type="delete" name="delete[]" id="{{$product->id}}"class="delete" >remove</button></td>
                </tr>
                @endforeach 
             <tfoot>
                 <tr>
                     <th id="ttl" colspan="4">Grandtotal :</th>
                     <td><input class="grandtotal" id="grandtotal" name="grandtotal" value="{{$order->total}}" readonly ></td>
                 </tr>
             </tfoot>
          </tbody>
   </table>
     
       <button type="submit" class="btn btn-success" >save</button> 
     
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        var rowIdx = $('#tbody tr').length;
        $('#addBtn').on('click', function () {
        var flag =0;
            $('.product').each(function(){

             if ($(this).val()==''){
                flag=1;
             }
            });
            if(flag==0){
            $('#tbody').append(`<tr id="R${++rowIdx}">
                <td class="row-index text-center">
                <p>${rowIdx}</p></td>
                <td>
                    <select class="product" name="product[]" id="product" required>
                    <option value=''>Select product</option>
                  @foreach ($data as $row)
                    <option value="{{ $row->id }}" >{{$row->product }} 
                    </option>
                  @endforeach    
                    </select>
                </td>
                <td><input class="rate" id="rate" name="rate[]"required></td>
                <td><input class="quantity" id="quantity" name="quantity[]"required></td>
                <td><input class="total" id="total" name="total[]"readonly></td>
                <td><button type="delete" class="delete" >remove</button></td>
                </tr>`);
            }
           });
        $('#tbody').on("change","#product",function(){
            var parent = $(this).closest('tr');
            var pdct =$(parent).find('#product').val();
            $.ajax({
                type : 'get',
                url : '{{url("order/fetchRate")}}/'+pdct,
                data:{p:pdct},
                success: function(data){
                console.log(data);
                $(parent).find('#rate').val(data.rate);
                var c = calculate (parent);
                $(parent).find('#rate').val(c);
          }
      });

  });

         $('#tbody').on("change","#product",function(){
            var parent = $(this).closest('tr');
            var qntity = parent.find(".quantity").val("");
            var ttl    = parent.find(".total").val("");
             $(parent).$val(qntity);
             $(parent).$val(ttl); 


        });
        
        

        $('#tbody').on("keyup",".rate,.quantity",function(){
            var parent = $(this).closest('tr');
            var price =Number($(parent).find('.rate').val());
            var qntity = Number($(parent).find('.quantity').val());
            var ttl = Number(parseInt(price* qntity));
            if (price == "0" ){
                ttl=0;
                }
            if (qntity == "0" ){
                ttl=0; 
                }
            $(parent).find('.total').val(ttl); 
            grandTotal();
            });  


        function grandTotal(){
            var sum= 0;
            $('.total').each(function() {
            sum += parseInt($(this).val()|| 0);
            });
            $('#grandtotal').val(sum);
        }

        $("#mytable").on('click', '.delete', function () {
        var x = confirm("are you sure");

        if(x==1){
            var z = $(this).attr('id');
            if(z!= undefined){

        $('#edit_form').append('<td><input type="hidden" id="edit_delete" name="edit_delete[]" value="'+z+'"></td>');

       }
        
        $(this).closest('tr').remove();
            grandTotal(); 
       }
       var i =1;
       $('#tbody tr').each(function(){
      $(this).closest('tr').find('td:first-child').text(i);
      i++;

       });     

                     
    });

});


</script>  
@endsection 

loginpage/resources/views/order/index.blade.php
@extends('layouts.app')  
@section('content') 
<head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<div class="container">
      <h2>ORDER</h2>  
</div>
<div class="card-body">
   <div class="panel-body">
       Order:
     <a href="{{ url('/order/create') }}" class="btn btn-success">Create</a>
   </div> 
 </div> 

<table class="table table-bordered" >  
<thead>  
<tr>  
<th>  ID        </th>  
<th>  Serial_No </th>
<th>  Name      </th> 
<th>  Date      </th>
<th>  Delete    </th>
<th>  Edit      </th>  
<th>  Show      </th>    
</tr>  
</thead> 

 
<tbody>
    @if(isset($orders))
    @foreach($orders as $order)
    <tr border="none">
    <td>{{$order->id}}</td> 
    <td>{{$order->serial_No}}</td>   
    <td>{{$order->name}}</td>
    <td>{{date('d-m-Y', strtotime($order->date)) }}</td> 
    <td>
        <form action="{{ url('/order/'.$order->id)}}" method="post">  
                  @csrf  
                  @method('DELETE')  
                  <button class="btn btn-warning" type="submit">Delete</button>
                  </form>  
   </td>  
   <td>  
        <a href="{{url('/order/'.$order->id.'/edit/')}}" class="btn btn-info">Edit</a>
   </td>  
   <td>  
        <a href="{{url('/order/'.$order->id)}}" class="btn btn-primary">Show</a>

   </td>  
   </tr>
   @endforeach 
   @endif
</tbody>  
</table>  
@endsection  

loginpage/resources/views/order/show.blade.php
@extends('layouts.app')  
@section('content')  
<head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<div class="container">
      ORDER DETIALS 
</div>
@if(isset($orders)) 
    @foreach($orders as $order)
<div class="form-group">  
     <label for="serial_No">Sl.No: 
    <input type="text" class="form-control" name="name" value="{{$order->serial_No}}"readonly>
    </label><br/><br/>   

<div class="form-group">      
              <label for="name">Name:  
              <input type="text" class="form-control" name="name" value="{{$order->name}}"readonly>
              </label><br/><br/>  
        </div>
        <div class="form-group">      
              <label for="date">Date:  
              <input type="date" class="form-control" name="date" value="{{($order->date) }}"readonly>
              </label><br/><br/>  
        </div>      @endforeach
        @endif


<table id="mytable" class="table table-bordered"> 
       <thead>
             <th>ID </th>
             <th>Product</th>
             <th>Rate</th>
             <th>Quantity</th>
             <th>Total</th>
       </thead>
           <tbody id="tbody" class="tbody">
           @foreach($products as $data) 
            <tr id="R${++rowIdx}">
                <td class="row-index text-center">
                <p>{{$loop->iteration}}</p></td>
                <td>
                    {{$data->order->product}}
                   
                </td>
                <td> {{$data->rate}}</td>
                <td>{{$data->quantity}}</td>
                <td>{{$data->total}}</td>
                </tr>
                @endforeach 
             <tfoot>
                 <tr>
                     <th colspan="4">Grandtotal :</th>
                     <td>{{$orders->sum('total')}}</td>
                 </tr>
             </tfoot>
          </tbody>
   </table>    

<div class="card-body">
    <div class="panel-body">
        back to page
        <a href="{{ url('/order') }}">back</a>
    </div>
</div> 
@endsection 
                             