loginpage/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\superUserController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('home', [HomeController::class, 'index'])->name('home'); 
Route::group(['middleware' => ['super_admin']], function () {
Route::get('super_admin-view', [HomeController::class, 'super_adminView'])->name('super_admin.view');
}); 


Route::resource('order', OrderController::class);
Route::get('/order/fetchRate/{p}', 'OrderController@fetchRate');

Route::resource('user',UserController::class);
Route::resource('customer',CustomerController::class);
Route::resource('employee',EmployeeController::class);

//Route::get('/order/index', 'OrderController@index');
// Route::get('/order/create', 'OrderController@create');
// Route::get('/order/store', 'OrderController@store');
// Route::get('/order/show/{id}', 'OrderController@show');
// Route::get('/order/edit/{id}', 'OrderController@edit');
// Route::get('/order/update/{id}', 'OrderController@update');
// Route::get('/order/destroy/{id}','OrderController@destroy');

loginpage/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'username', 'password', 'rollid','is_permission'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function role()
    {
        return $this->belongsTo('App\Role','rollid');
    }

}
 

loginpage/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Role;

use Illuminate\Http\Request;

class UserController extends Controller
{
   public function index()
    {
         $users = User::join('rolls','rolls.id' , '=', 'users.rollid')
                
       ->selectRaw('users.id,users.name,rolls.roll')
       ->get();
        return view('user/index', compact('users'));
    }
   public function edit(Request $request, $id)  
    {  
       $user    = User::find($id);
       $data     = Role::all(); 
       return view('user/edit', compact('user','data')); 
    }
   public function update(Request $request, $id)
    {
        $user = User::where('id', $id)->update([
            'name'   => $request->name,
            'rollid' => $request->rollid,
            ]);
            
        return redirect('user');  
    }
   public function destroy($id)  
    {  
       $user=User::find($id);  
       $user->delete();

       return redirect('user');  
    } 

}

loginpage/resources/views/user/edit.blade.php
@extends('layouts.app') 
@section('content')  
<head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<form method="POST" id="edit_form"action="{{route('user.update',$user->id)}}">
    @csrf 
    @method('PUT')     
   
            
        <div class="form-group">      
              <label for="name">Name:  
              <input type="text" class="form-control" name="name" value="{{$user->name}}">
              </label><br/><br/>  
        </div>             
        <div>
          <label for="role">Roll:
              <select class="role" name="rollid" id="role" >
                    <option value=''>Select role</option>
                  @foreach ($data as $row)
                    <option value="{{ $row->id }}" >{{$row->roll }} 
                    </option>
                  @endforeach    
                    </select>
                    </label><br/><br/>
        </div>
       <button type="submit" class="btn btn-success" >save</button> 
     
</form>




@endsection 

loginpage/resources/views/user/index.blade.php
@extends('layouts.app')  
@section('content')

<head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<div class="container">
      <h2>user detials</h2>  
</div>

<a href="{{ url('/order') }}">Check order</a><br>


<table class="table table-bordered" >  
<thead>  
<tr>   
<th>  Name      </th> 
<th>  Roll     </th>
<th>  Delete    </th>
<th>  Edit      </th>     
</tr>  
</thead> 

 
<tbody>
    @if(isset($users))
    @foreach($users as $user)
    <tr border="none"> 
    <td>{{$user->name}}</td>   
    <td>{{($user->roll) }}</td>
    <td><form action="{{ url('/user/'.$user->id)}}" method="post">  
                  @csrf  
                  @method('DELETE')  
                  <button class="btn btn-warning" type="submit">Delete</button>
                  </form></td>
    <td>  
        <a href="{{url('/user/'.$user->id.'/edit/')}}" class="btn btn-info">Edit</a>
   </td>
    
   </tr>
   @endforeach 
   @endif
</tbody>  
</table>  
@endsection  