loginpage/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\superUserController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('home', [HomeController::class, 'index'])->name('home'); 
Route::group(['middleware' => ['super_admin']], function () {
Route::get('super_admin-view', [HomeController::class, 'super_adminView'])->name('super_admin.view');
}); 


Route::resource('order', OrderController::class);
Route::get('/order/fetchRate/{p}', 'OrderController@fetchRate');

Route::resource('user',UserController::class);
Route::resource('customer',CustomerController::class);
Route::resource('employee',EmployeeController::class);

//Route::get('/order/index', 'OrderController@index');
// Route::get('/order/create', 'OrderController@create');
// Route::get('/order/store', 'OrderController@store');
// Route::get('/order/show/{id}', 'OrderController@show');
// Route::get('/order/edit/{id}', 'OrderController@edit');
// Route::get('/order/update/{id}', 'OrderController@update');
// Route::get('/order/destroy/{id}','OrderController@destroy');

loginpage/app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
   protected $table='employees';  
   protected $fillable=['id','name','date_of_birth','phone_no','address','pincode','designation_id','date_of_joining','image_path'];  

   public function designation()
    {
        return $this->belongsTo('App\Designation','designation_id');
    }

}

loginpage/app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;
use App\Designation;

class EmployeeController extends Controller
{
    public function index()
    {
        $employees = Employee::all();   
        return view('employee/index', compact('employees'));
    }
    public function create(Request $request)
    {
        $data = Designation::all();

        return view('employee/create', compact('data')); 
    }
    public function store(Request $request)  
    {  
        
        //dd($request->all());
       $request->validate([  
            'name'                =>'required',
            'date_of_birth'       =>'required|before:20 years ago',
            'phone_no'            =>'required|unique:employees|digits:10',
            'address'             =>'required', 
            'pincode'             =>'required|digits:6',
            'designation_id'      =>'required',
            'date_of_joining'     =>'required|date_format:Y-m-d|before:today',
        ]);

        $newImageName= time() . '-' . $request->name . '-' .
        $request->image->extension();
        $request->image->move(public_path('images'), $newImageName);

      
      $employees = Employee::create([
        'name'            => $request->name,
        'date_of_birth'   => $request->date_of_birth,
        'phone_no'        => $request->phone_no,
        'address'         => $request->address,
        'pincode'         => $request->pincode,
        'designation_id'  => $request->designation_id,
        'date_of_joining' => $request->date_of_joining,
        'image_path'      => $newImageName,

        ]);

      return redirect('employee');
      }
      public function edit(Request $request, $id)  
    {  
       $data      = Designation::all(); 
       $employees = Employee::where('id', $id)->first();
       return view('employee/edit', compact('data', 'employees')); 
    }  
    public function update(Request $request, $id)
   {
     $request->validate([  
            'name'                =>'required',
            'date_of_birth'       =>'required|before:20 years ago',
            'phone_no'            =>'required|digits:10',
            'address'             =>'required', 
            'pincode'             =>'required|digits:6',
            'designation_id'      =>'required',
            'date_of_joining'     =>'required|date_format:Y-m-d|before:today',
            
        ]);

        $newImageName=null;
        if($request->image!=null){
        $newImageName= time() . '-' . $request->address . '-' .
        $request->image->extension();
        $request->image->move(public_path('images'), $newImageName);
        }
        

      $employees = Employee::find($id)->update([
        'name'            => $request->name,
        'date_of_birth'   => $request->date_of_birth,
        'phone_no'        => $request->phone_no,
        'address'         => $request->address,
        'pincode'         => $request->pincode,
        'designation_id'  => $request->designation_id,
        'date_of_joining' => $request->date_of_joining,
        'image_path'      => $newImageName,

        ]);
        
        return redirect('employee');
         }
    public function show($id){
    $employees  = Employee::find (array($id));
    return view('employee/show', compact('employees'));
    }  
    public function destroy($id)  
    {  
       $employees=Employee::find($id);  
       $employees->delete();

       return redirect('employee');  
    }  

}

loginpage/resources/views/employee/create.blade.php
@extends('layouts.app') 
@section('content')

<form method="POST" action="{{route('employee.store')}}" enctype="multipart/form-data">
    @csrf    
          
        <div class="form-group">      
              <label for="name">Name:  
              <input type="text" class="form-control" name="name" placeholder="name" required>
              </label><br/><br/> 
        </div>
        <div class="form-group">      
              <label for="date">Date of birth  : 
              <input type="date" class="form-control" name="date_of_birth" required>
              </label><br/><br/>  
        </div>   
        <div class="form-group">      
              <label for="phone_no">Phone no :  
              <input type="text" class="form-control" name="phone_no" placeholder="phone no" required>
              </label><br/><br/> 
        </div>
        <div class="form-group">      
              <label for="address">Address  :  
              <textarea class="form-control" style="height:150px" name="address" placeholder="address" required></textarea>
              </label><br/><br/> 
        </div>
        <div class="form-group">      
              <label for="pincode">Pincode  :  
              <input type="text" class="form-control" name="pincode" placeholder="pincode" required>
              </label><br/><br/> 
        </div>
        <div>
          <label for="designation_id">Designation:
              <select class="designation_id" name="designation_id" id="designation_id" required>
                    <option value=''>Select designation</option>
                  @foreach ($data as $row)
                    <option value="{{ $row->id }}" >{{$row->designation }} 
                    </option>
                  @endforeach    
                    </select>
                    </label><br/><br/>
        </div>
        <div class="form-group">      
              <label for="date">Date of joining  : 
              <input type="date" class="form-control" name="date_of_joining" required>
              </label><br/><br/>  
        </div>
        <div class="form-group">
                <strong>Image:</strong>
                <input type="file" name="image" class="form-control" >
        </div><br/><br/>             
     <footer>
       <button type="submit" class="btn-btn" >save</button> 
     </footer> 
</form>



@endsection 

loginpage/resources/views/employee/edit.blade.php
<form method="POST" id="edit_form"action="{{route('employee.update',$employees->id)}}" enctype="multipart/form-data">
    @csrf 
    @method('PUT')  

       <div class="form-group">      
              <label for="name">Name:  
              <input type="text" class="form-control" name="name"  value="{{$employees->name}}"required>
              </label><br/><br/> 
        </div>
        <div class="form-group">      
              <label for="date">Date of birth  : 
              <input type="date" class="form-control" name="date_of_birth" value="{{$employees->date_of_birth}}" required>
              </label><br/><br/>  
        </div>   
        <div class="form-group">      
              <label for="phone_no">Phone no :  
              <input type="text" class="form-control" name="phone_no"  value="{{$employees->phone_no}}" required>
              </label><br/><br/> 
        </div>
        <div class="form-group">      
              <label for="address">Address  :  
              <input type="text"class="form-control"  name="address"  value="{{$employees->address}}" required>
              </label><br/><br/> 
        </div>
        <div class="form-group">      
              <label for="pincode">Pincode  :  
              <input type="text" class="form-control" name="pincode"  value="{{$employees->pincode}}" required>
              </label><br/><br/> 
        </div>
        <div>
          <label for="designation_id">Designation:
              <select class="designation_id" name="designation_id" id="designation_id" required>
                    <option value=''>Select designation</option>
                  @foreach ($data as $row)
                    <option value="{{ $row->id }}"  @if (old('designation_id') == $row->id || $row->id == $employees->designation_id)selected  @endif  >{{$row->designation }} 
                    </option>
                  @endforeach    
                    </select>
                    </label><br/><br/>
        </div>
        <div class="form-group">      
              <label for="date">Date of joining  : 
              <input type="date" class="form-control" name="date_of_joining"  value="{{$employees->date_of_joining}}"required>
              </label><br/><br/>  
        </div>
       <p>
                <input type="file" name="image" onchange="previewFile(this);">
            </p>
            <div class="stn_uploader">
            <button type="button" class="delete">Remove</button><br>
            <div></br>
            <img id="previewImg" src="{{ URL::asset('images/'.$employees->image_path )}}" alt="Placeholder">
            </div>
            </div><br>
                    
       <button type="submit" class="btn btn-success" >save</button> 
     
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>

    function previewFile(input){
            var file = $("input[type=file]").get(0).files[0];
            if(file){
                var reader = new FileReader();
                reader.onload = function(){
                    $("#previewImg").attr("src", reader.result);
                }
     
                reader.readAsDataURL(file);
            }
        }


     $(document).ready(function() {
    $('.stn_uploader .delete').click(function() {
          $(this).closest('.stn_uploader').find('img').remove();  
    });
});


  
</script>
  

loginpage/resources/views/employee/index.blade.php
@extends('layouts.app')  
@section('content') 
<head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<div class="container">
      <h2>EMPLOYEE</h2>  
</div>
<div class="card-body">
   <div class="panel-body">
       Employee:
     <a href="{{ url('/employee/create') }}" class="btn btn-success">Create</a>
   </div> 
 </div> 
<table class="table table-bordered" >  
<thead>  
<tr>  
<th>  ID                 </th>  
<th>  Name               </th> 
<th>  Date of birth      </th> 
<th>  Phone no           </th>
<th>  Address            </th> 
<th>  Pincode            </th> 
<th>  Designation        </th> 
<th>  Date of joining    </th> 
<th>  Delete             </th>
<th>  Edit               </th>  
<th>  Show               </th>    
</tr>  
</thead> 

 
<tbody>
    @if(isset($employees))
    @foreach($employees as $employee)
    <tr border="none">
    <td>{{$employee->id}}</td> 
    <td>{{$employee->name}}</td>
    <td>{{date('d-m-Y', strtotime($employee->date_of_birth)) }}</td> 
    <td>{{$employee->phone_no}}</td>
    <td>{{$employee->address}}</td>
    <td>{{$employee->pincode}}</td>
    <td>{{$employee->designation->designation}}</td>
    <td>{{date('d-m-Y', strtotime($employee->date_of_joining)) }}</td> 
    <td>
        <form action="{{ url('/employee/'.$employee->id)}}" method="post">  
                  @csrf  
                  @method('DELETE')  
                  <button class="btn btn-warning" type="submit">Delete</button>
                  </form>  
   </td>  
   <td>  
        <a href="{{url('/employee/'.$employee->id.'/edit/')}}" class="btn btn-info">Edit</a>
   </td>  
   <td>  
        <a href="{{url('/employee/'.$employee->id)}}" class="btn btn-primary">Show</a>

   </td>  
   </tr>
   @endforeach 
   @endif
</tbody>  
</table>  
@endsection  

loginpage/resources/views/employee/show.blade.php
<div class="container">
      EMPLOYEE DETIALS 
</div><br>
@if(isset($employees)) 
    @foreach($employees as $employee)
    <div class="form-group">      
              <label for="name">Name: {{$employee->name}}
              </label><br/><br/> 
        </div>
        <div class="form-group">      
              <label for="date">Date of birth  : {{date('d-m-Y', strtotime($employee->date_of_birth)) }}
              </label><br/><br/>  
        </div>   
        <div class="form-group">      
              <label for="phone_no">Phone no : {{$employee->phone_no}} 
              </label><br/><br/> 
        </div>
        <div class="form-group">      
              <label for="address">Address  :  {{$employee->address}}
              </label><br/><br/> 
        </div>
        <div class="form-group">      
              <label for="pincode">Pincode  :  {{$employee->pincode}}
              </label><br/><br/> 
        </div>
        <div>
          <label for="designation_id">Designation:{{$employee->designation->designation}}
              </label><br/><br/>
        </div>
        <div class="form-group">      
              <label for="date">Date of joining  : {{date('d-m-Y', strtotime($employee->date_of_joining)) }}
              </label><br/><br/>  
        </div>
        @if($employee->image_path!=null)
        <div class="form-group">
        <img src="{{ URL::asset('images/'.$employee->image_path )}}" >
         image 
   @endif 
    </div><br/><br/> 
        @endforeach
        @endif
        <div class="card-body">
        <div class="panel-body">
        back to page
        <a href="{{ url('/employee') }}">back</a>
       </div>
       </div> 

  