loginpage/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\superUserController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('home', [HomeController::class, 'index'])->name('home'); 
Route::group(['middleware' => ['super_admin']], function () {
Route::get('super_admin-view', [HomeController::class, 'super_adminView'])->name('super_admin.view');
}); 


Route::resource('order', OrderController::class);
Route::get('/order/fetchRate/{p}', 'OrderController@fetchRate');

Route::resource('user',UserController::class);
Route::resource('customer',CustomerController::class);
Route::resource('employee',EmployeeController::class);

//Route::get('/order/index', 'OrderController@index');
// Route::get('/order/create', 'OrderController@create');
// Route::get('/order/store', 'OrderController@store');
// Route::get('/order/show/{id}', 'OrderController@show');
// Route::get('/order/edit/{id}', 'OrderController@edit');
// Route::get('/order/update/{id}', 'OrderController@update');
// Route::get('/order/destroy/{id}','OrderController@destroy');

loginpage/app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
   
   protected $table='customers';  
   protected $fillable=['id','name']; 

}

loginpage/app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Customer;

class CustomerController extends Controller
{
    public function index()
    {
        $customers=Customer::all();
        return view('customer/index',compact('customers'));
    }
     public function create()
    {
        $customers=Customer::all();
        return view('customer/create',compact('customers'));
    }
     public function store(Request $request)
    {
         $request->validate([
    
    'customer.name' => 'required',
    
]);
        $customers = Customer::create([   
            'name'   => $request->name,
            ]);
        return redirect('customer');
    }
    public function edit(Request $request, $id)
    {

        $customers = Customer::find($id);
        return view('customer/edit',compact('customers'));
    }
    public function update(Request $request, $id)
    {      
       
       $customers = Customer::where('id', $id)->update([

            
            'name'   => $request->name,
            ]);
          return redirect('customer');
    }
    public function destroy($id)
    {

         $customers=Customer::find($id);  
       $customers->delete();
        return redirect('customer');

    }
}

loginpage/resources/views/customer/create.blade.php
@extends('layouts.app') 
@section('content') 
<form method="POST" action="{{route('customer.store')}}">
    @csrf    
           
        <div class="form-group">      
              <label for="name">Name:  
              <input type="text" class="form-control" name="name">
              </label><br/><br/> 
        </div>
     <div>
       <button type="submit" class="btn-btn" >save</button> 
     </div> 
</form>

loginpage/resources/views/customer/edit.blade.php
@extends('layouts.app') 
@section('content') 
<h2>this is your edit page</h2>
<form  method="POST" action="{{route('customer.update',$customers->id)}}">
     @csrf 
    @method('PUT')  

<table class="table table-bordered" border="1px">

         <div class="form-group">      
              <label>ID : {{$customers->id}}
              </label><br/><br/>  
        </div>
           <div class="form-group">      
              <label for="name">Name:  
              <input type="text" class="form-control" name="name" value="{{$customers->name}}">
              </label><br/><br/>  
        </div>
            
        <button type="submit" class="btn btn-success" >save</button>
        </form>
        @endsection 

loginpage/resources/views/customer/index.blade.php
@extends('layouts.app') 
@section('content') 
<h2>welcome here</h2>
 <div class="panel-body">
       Customer:
     <a href="{{ url('/customer/create') }}" class="btn btn-success">Create</a>
   </div> 
<table class="table table-bordered" border="1px">
	<thead>
	<tr>
	<th>Id</th>
	<th>Name</th>
	<th>Edit</th>
	<th>Delete</th>
	</tr>
	</thead>
<tbody>
	@foreach($customers as $customer)
	<tr >
        <td class="row-index text-center">
        <p>{{$customer->id}}</p></td>
		<td>{{$customer->name}}</td>
	    <td>
	      <a href="{{url('/customer/'.$customer->id.'/edit/')}}" class="btn btn-info">edit</a>

	  </td>
	  <td>
        <form action="{{ url('/customer/'.$customer->id)}}" method="post">  
                  @csrf  
                  @method('DELETE')  
                  <button class="btn btn-warning" type="submit">Delete</button>
                  </form>  
   </td>  
	    
	  
    </tr>
	@endforeach
</tbody>
</table>
@endsection 